### ISSUE TITLE
Use X509 certificate

### ISSUE THREAD

**Issue by stagiairethuasne** [lucadruda/iotc-react-native-device-client#5]
Hello,

To begin, thank you for all your work.
I am using your library react-native-azure-iotcentral-client (version 1.1.7) in order to connect to Azure iotCentral in a react-native application.
Your library was working fine when I was using a device_key, but now I would like to use a X509 certifcate. However, I can't manage to make it works. 
Here is a snippet of how I tried to do it : 

`const scopeId = '000000000'; //Scope id
 const deviceId = 'TEST'; //Device id
 const certFile =  '-----BEGIN CERTIFICATE-----*****-----END CERTIFICATE-----';
 const certKey = '-----BEGIN RSA PRIVATE KEY-----******-----END RSA PRIVATE KEY-----'
 const modelId = '****'; //interfaceID
 let X509 = {certFile, certKey};
 this.iotc = new IoTCClient( deviceId, scopeId, IOTC_CONNECT.DEVICE_KEY, X509,); 
 this.iotc.setModelId(modelId); //set IoTC template ID in your device`
 
 I saw that there is an interface named X509 in your library, but I can't make interface works in Javascript. I also tried to do `JSON.stringify(X509)`, but I am still not authorized to connect to Azure. 
 
 Finally, I don't know which method I should use with IOTC_CONNECT. I only have DEVICE_KEY or SYMM_KEY. I saw that you have also CONN_STRING, but it doesn't appear in my code.
 
If you need anything else to help me, please just let me know. 

Clément

**Comment by lucadruda** [comment]
Hi, 
current version of the library does not support x509 yet. The interface you see there is a placeholder and will be refactored in version 1.2.0 coming out soon. That same version will include support for x509.
